name: Deploy to Github Pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i --legacy-peer-deps
      - name: Push changes
        uses: ptienchuan/deploy-github-pages-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: "build"
          target-branch: "gh-pages"
          user-name: "nagaraju sangam"
          user-email: "nagaraju_sangam@yahoo.co.in"
